# Site settings
title           : Code For FoCo
url             : "http://codeforfoco.org"
baseurl         : ""
email           : people@codeforfoco.org
github_username : codeforfoco
description: > # this means to ignore newlines until next yaml item
  We are programmers, designers, hackers, makers, tinkerers,
  writers and artists and we want to have an impact on the community
  around us.

# Reading files
encoding: "utf-8"
markdown_ext: "md"

# Conversion
markdown: kramdown
highlighter: rouge

# Markdown processing
kramdown:
  input: GFM

# Sass/SCSS
sass:
  sass_dir: _sass
  style: nested
#  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.htm

# Outputting
permalink: pretty

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Serving
port          : 8080